hisilicon: hdmi: fix self assign found by clang
Clang complains about the self assign as below.

drivers/hisilicon/msp/hdmi/hdmi_2_0/hal/ctrl/imagev200/platform/platform.c:42:26: error: explicitly assigning value
      of variable of type 'uint32_t' (aka 'unsigned int') to itself [-Werror,-Wself-assign]
    expressionEvaluation = expressionEvaluation; //to avoid compiler warnings about unused variable
    ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~
drivers/hisilicon/msp/hdmi/hdmi_2_0/hal/ctrl/imagev200/platform/platform.c:43:21: error: explicitly assigning value
      of variable of type 'const char *' to itself [-Werror,-Wself-assign]
    pConditionText       = pConditionText; // to avoid compiler warnings about unused variable
    ~~~~~~~~~~~~~~       ^ ~~~~~~~~~~~~~~
drivers/hisilicon/msp/hdmi/hdmi_2_0/hal/ctrl/imagev200/platform/platform.c:46:15: error: explicitly assigning value
      of variable of type 'const char *' to itself [-Werror,-Wself-assign]
    pFileName = pFileName; // to avoid compiler warnings about unused variable
    ~~~~~~~~~ ^ ~~~~~~~~~
drivers/hisilicon/msp/hdmi/hdmi_2_0/hal/ctrl/imagev200/platform/platform.c:47:16: error: explicitly assigning value
      of variable of type 'uint32_t' (aka 'unsigned int') to itself [-Werror,-Wself-assign]
    lineNumber = lineNumber; // to avoid compiler warnings about unused variable
    ~~~~~~~~~~ ^ ~~~~~~~~~~
4 errors generated.

Fix them by removing the self assignments.

Change-Id: I7d283ba0344f389a7c006937b68463f256a5c02b
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>