hisilicon: mmz: fix typedef redefinition found by clang
Clang complains about typedef redefinitions like below.

In file included from drivers/hisilicon/common/mmz/drv_mmz_intf.c:37:
./drivers/hisilicon/common/mmz/drv_media_mem.h:20:23: error: redefinition of typedef 'HI_U32' is a C11 feature
      [-Werror,-Wtypedef-redefinition]
typedef unsigned int            HI_U32;
                                ^
./drivers/hisilicon/sdk/common-include/hi_type.h:38:23: note: previous definition is here
typedef unsigned int            HI_U32;
                                ^
1 error generated.

Fix it by removing the redefinitions as the types have been defined in
drivers/hisilicon/sdk/common-include/hi_type.h.

Change-Id: Ia0ca34b355a5520de16e9fdb66273282ee443e27
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>