hisilicon: msp: fix redefinition in hi_init.c
Clang complains the following redefinitions in hi_init.c.

In file included from drivers/hisilicon/msp/base/hi_init.c:28:
./drivers/hisilicon/msp/include/drv_jpge_ext.h:30:19: error: redefinition of typedef 'FN_JPGE_ModInit' is a C11
      feature [-Werror,-Wtypedef-redefinition]
typedef HI_S32   (*FN_JPGE_ModInit)(HI_VOID);
                   ^
./drivers/hisilicon/msp/include/drv_jpeg_ext.h:30:19: note: previous definition is here
typedef HI_S32   (*FN_JPGE_ModInit)(HI_VOID);
                   ^
In file included from drivers/hisilicon/msp/base/hi_init.c:28:
./drivers/hisilicon/msp/include/drv_jpge_ext.h:31:20: error: redefinition of typedef 'FN_JPGE_ModeExit' is a C11
      feature [-Werror,-Wtypedef-redefinition]
typedef HI_VOID  (*FN_JPGE_ModeExit)(HI_VOID);
                   ^
./drivers/hisilicon/msp/include/drv_jpeg_ext.h:31:20: note: previous definition is here
typedef HI_VOID  (*FN_JPGE_ModeExit)(HI_VOID);
                   ^
2 errors generated.

It turns out that neither drv_jpge_ext.h nor drv_jpeg_ext.h is needed by
hi_init.c.  Remove both includes to fix the error.

Change-Id: Ia48e44857f9f2d100c4960978def2be3b7e73b89
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>